apiVersion: v1
kind: Secret
metadata:
  name: lifeline-secrets
  namespace: lifeline
type: Opaque
stringData:
  LIFELINE_DB_PASSWORD: "REPLACE_ME_DATABASE_PASSWORD"
  LIFELINE_JWT_SECRET: "REPLACE_ME_RANDOM_32_PLUS_CHARACTER_SECRET"
  LIFELINE_DEMO_PASSWORD: "REPLACE_ME_DEMO_PASSWORD"
